### ISSUE TITLE
Runtime Error in Match halfway

### ISSUE THREAD

**Issue by AndynWhen** [cvg/Hierarchical-Localization#8]
Thanks for your works!
When I'm running **pipeline_Aachen.ipydb**,  error occurs at the step **Match the database images** halfway.
The error information is listed as follows, my device GTX 1080Ti &&  Memory 15.6GB:

RuntimeError                              Traceback (most recent call last)
<ipython-input-5-2265bc492996> in <module>()
----> 1 match_features.main(matcher_conf, sfm_pairs, feature_conf['output'], outputs)

~/anaconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py in decorate_no_grad(*args, **kwargs)
     47         def decorate_no_grad(*args, **kwargs):
     48             with self:
---> 49                 return func(*args, **kwargs)
     50         return decorate_no_grad
     51 

~/code/Hierarchical-Localization/hloc/match_features.py in main(conf, pairs, features, export_dir, exhaustive)
     97         data['image1'] = torch.empty((1, 1,)+tuple(feats1['image_size'])[::-1])
     98 
---> 99         pred = model(data)
    100         grp = match_file.create_group(pair)
    101         matches = pred['matches0'][0].cpu().short().numpy()

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/code/Hierarchical-Localization/hloc/utils/base_model.py in forward(self, data)
     20         for key in self.required_data_keys:
     21             assert key in data, 'Missing key {} in data'.format(key)
---> 22         return self._forward(data)
     23 
     24     @abstractmethod

~/code/Hierarchical-Localization/hloc/matchers/superglue.py in _forward(self, data)
     23 
     24     def _forward(self, data):
---> 25         return self.net(data)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/code/Hierarchical-Localization/SuperGluePretrainedNetwork/models/superglue.py in forward(self, data)
    251 
    252         # Multi-layer Transformer network.
--> 253         desc0, desc1 = self.gnn(desc0, desc1)
    254 
    255         # Final MLP projection.

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/code/Hierarchical-Localization/SuperGluePretrainedNetwork/models/superglue.py in forward(self, desc0, desc1)
    136             else:  # if name == 'self':
    137                 src0, src1 = desc0, desc1
--> 138             delta0, delta1 = layer(desc0, src0), layer(desc1, src1)
    139             desc0, desc1 = (desc0 + delta0), (desc1 + delta1)
    140         return desc0, desc1

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/code/Hierarchical-Localization/SuperGluePretrainedNetwork/models/superglue.py in forward(self, x, source)
    117 
    118     def forward(self, x, source):
--> 119         message = self.attn(x, source, source)
    120         return self.mlp(torch.cat([x, message], dim=1))
    121 

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/code/Hierarchical-Localization/SuperGluePretrainedNetwork/models/superglue.py in forward(self, query, key, value)
    104         query, key, value = [l(x).view(batch_dim, self.dim, self.num_heads, -1)
    105                              for l, x in zip(self.proj, (query, key, value))]
--> 106         x, prob = attention(query, key, value)
    107         self.prob.append(prob)
    108         return self.merge(x.contiguous().view(batch_dim, self.dim*self.num_heads, -1))

~/code/Hierarchical-Localization/SuperGluePretrainedNetwork/models/superglue.py in attention(query, key, value)
     85 def attention(query, key, value):
     86     dim = query.shape[1]
---> 87     scores = torch.einsum('bdhn,bdhm->bhnm', query, key) / dim**.5
     88     prob = torch.nn.functional.softmax(scores, dim=-1)
     89     return torch.einsum('bhnm,bdhm->bdhn', prob, value), prob

RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 10.91 GiB total capacity; 9.09 GiB already allocated; 19.62 MiB free; 10.09 GiB reserved in total by PyTorch)

  1%|          | 888/85515 [00:30<2:20:31, 10.04it/s]

Could you give some suggestions?Thanks a lot!

**Comment by Skydes** [comment]
10GB reserved by PyTorch is not normal. Are of you really running the latest commits of this repo? I recently pushed a fix https://github.com/cvg/Hierarchical-Localization/commit/77002d67d0a7114c640788433eb76353e7b160ad that reduces the memory requirements of SuperGlue.

**Comment by AndynWhen** [comment]
> 10GB reserved by PyTorch is not normal. Are of you really running the latest commits of this repo? I recently pushed a fix [77002d6](https://github.com/cvg/Hierarchical-Localization/commit/77002d67d0a7114c640788433eb76353e7b160ad) that reduces the memory requirements of SuperGlue.

Oh I did use the original version,now it works normally! 
By the way, did you test the model based on SuperPoint-Pairs from NetVLad and covisibility constraint (Here is Sift-Pairs from Colmap model)? Maybe the result of localization can be more accurate.

**Comment by Skydes** [comment]
Using NetVLAD for the SfM pairs should work well too, but is less robust if there are too many self-similarities.
